flyway.url=jdbc:postgresql://postgres:5432/medassist
flyway.user=medassist_user
flyway.password=medassist_pass
flyway.schemas=public
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true